//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Talker;

/** @hidden */
public class _ChatClientPrxI extends com.zeroc.Ice._ObjectPrxI implements ChatClientPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
